=== VladDemyanovNew/JavaLabs/Java_Lab2/files/info.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Payments" type="PaymentsType"/>
  <xs:complexType name="ClientType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="lastName" use="optional"/>
        <xs:attribute type="xs:string" name="middleName" use="optional"/>
        <xs:attribute type="xs:string" name="passportData" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ClientsType">
    <xs:sequence>
      <xs:element type="ClientType" name="Client" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AdminType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="lastName" use="optional"/>
        <xs:attribute type="xs:string" name="middleName" use="optional"/>
        <xs:attribute type="xs:string" name="passportData" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="AdminsType">
    <xs:sequence>
      <xs:element type="AdminType" name="Admin" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PaymentsType">
    <xs:sequence>
      <xs:element type="ClientsType" name="Clients"/>
      <xs:element type="AdminsType" name="Admins"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== VladDemyanovNew/JavaLabs/Java_Lab2/files/info.xml
<?xml version="1.0" encoding="UTF-8"?>
<Payments xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="info.xsd">
    <Clients>
        <Client name="Vlad" lastName="Demyanov" middleName="Ruslanovich" passportData="123-sd-213-ppp" />
        <Client name="Alex" lastName="AlexLastName" middleName="AlexMiddleName" passportData="123-sd-213-spp" />
        <Client name="Pavel" lastName="PavelLastName" middleName="PavelMiddleName" passportData="123-sd-213-s54" />
        <Client name="Client4Name" lastName="Client4LastName" middleName="Client4MiddleName" passportData="124-sd-213-sdf" />
    </Clients>
    <Admins>
        <Admin name="Admin1Name" lastName="Admin1LastName" middleName="Admin1MiddleName" passportData="122-sd-213-sdf" />
        <Admin name="Admin2Name" lastName="Admin2LastName" middleName="Admin2MiddleName" passportData="125-sd-213-sdf" />
        <Admin name="Admin3Name" lastName="Admin3LastName" middleName="Admin3MiddleName" passportData="124-sd-213-sdf" />
        <Admin name="Admin3Name" lastName="Admin3LastName" middleName="Admin3MiddleName" passportData="1s3-sd-213-sdf" />
    </Admins>
</Payments>
